---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-claim
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
