version: "3.9"
services:
  gatus:
    image: twinproduction/gatus:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=gatususer # postgres user with access to the database
      - POSTGRES_PASSWORD=gatuspassword # postgres user password
      - POSTGRES_DB=postgres-rw # db name
    volumes:
      - ./config:/config